// Data for 78 Tarot Cards
// Includes Major Arcana and Minor Arcana (Wands, Cups, Swords, Pentacles)

const TAROT_DATA = [
    // Major Arcana (22)
    { id: 0, name_es: "El Loco", name_en: "The Fool", type: "major", number: 0, keywords_up: "Inocencia, nuevos comienzos, espíritu libre", keywords_rev: "Imprudencia, toma de riesgos, ingenuidad", img: "assets/images/placeholder.png" },
    { id: 1, name_es: "El Mago", name_en: "The Magician", type: "major", number: 1, keywords_up: "Poder, habilidad, concentración, acción", keywords_rev: "Manipulación, mala planificación, talentos latentes", img: "assets/images/placeholder.png" },
    { id: 2, name_es: "La Sacerdotisa", name_en: "The High Priestess", type: "major", number: 2, keywords_up: "Intuición, misterio, subconsciente", keywords_rev: "Secretos, desconexión de la intuición", img: "assets/images/placeholder.png" },
    { id: 3, name_es: "La Emperatriz", name_en: "The Empress", type: "major", number: 3, keywords_up: "Fertilidad, feminidad, belleza, naturaleza", keywords_rev: "Bloqueo creativo, dependencia", img: "assets/images/placeholder.png" },
    { id: 4, name_es: "El Emperador", name_en: "The Emperor", type: "major", number: 4, keywords_up: "Autoridad, estructura, control, paternidad", keywords_rev: "Tiranía, rigidez, frialdad", img: "assets/images/placeholder.png" },
    { id: 5, name_es: "El Sumo Sacerdote", name_en: "The Hierophant", type: "major", number: 5, keywords_up: "Tradición, conformidad, moralidad, ética", keywords_rev: "Rebelión, nuevas creencias, inconformismo", img: "assets/images/placeholder.png" },
    { id: 6, name_es: "Los Enamorados", name_en: "The Lovers", type: "major", number: 6, keywords_up: "Amor, unión, relaciones, alineación de valores", keywords_rev: "Desarmonía, desequilibrio, desalineación", img: "assets/images/placeholder.png" },
    { id: 7, name_es: "El Carro", name_en: "The Chariot", type: "major", number: 7, keywords_up: "Control, voluntad, éxito, acción, determinación", keywords_rev: "Falta de control, agresión, obstáculos", img: "assets/images/placeholder.png" },
    { id: 8, name_es: "La Fuerza", name_en: "Strength", type: "major", number: 8, keywords_up: "Coraje, persuasión, influencia, compasión", keywords_rev: "Duda, falta de confianza, debilidad", img: "assets/images/placeholder.png" },
    { id: 9, name_es: "El Ermitaño", name_en: "The Hermit", type: "major", number: 9, keywords_up: "Introspección, soledad, guía interior", keywords_rev: "Aislamiento, soledad, retirada", img: "assets/images/placeholder.png" },
    { id: 10, name_es: "La Rueda de la Fortuna", name_en: "Wheel of Fortune", type: "major", number: 10, keywords_up: "Buen karma, ciclos de vida, destino, un punto de inflexión", keywords_rev: "Mala suerte, resistencia al cambio", img: "assets/images/placeholder.png" },
    { id: 11, name_es: "La Justicia", name_en: "Justice", type: "major", number: 11, keywords_up: "Justicia, imparcialidad, verdad, causa y efecto", keywords_rev: "Injusticia, falta de responsabilidad, deshonestidad", img: "assets/images/placeholder.png" },
    { id: 12, name_es: "El Colgado", name_en: "The Hanged Man", type: "major", number: 12, keywords_up: "Pausa, rendición, dejar ir, nuevas perspectivas", keywords_rev: "Retrasos, resistencia, estancamiento", img: "assets/images/placeholder.png" },
    { id: 13, name_es: "La Muerte", name_en: "Death", type: "major", number: 13, keywords_up: "Fin, transformación, transición, cambio", keywords_rev: "Resistencia al cambio, incapacidad de avanzar", img: "assets/images/placeholder.png" },
    { id: 14, name_es: "La Templanza", name_en: "Temperance", type: "major", number: 14, keywords_up: "Equilibrio, moderación, paciencia, propósito", keywords_rev: "Desequilibrio, exceso, falta de armonía", img: "assets/images/placeholder.png" },
    { id: 15, name_es: "El Diablo", name_en: "The Devil", type: "major", number: 15, keywords_up: "Sombra, apego, adicción, restricción, sexualidad", keywords_rev: "Liberación, recuperar el poder, desapego", img: "assets/images/placeholder.png" },
    { id: 16, name_es: "La Torre", name_en: "The Tower", type: "major", number: 16, keywords_up: "Cambio repentino, agitación, caos, revelación", keywords_rev: "Evitar el desastre, miedo al cambio", img: "assets/images/placeholder.png" },
    { id: 17, name_es: "La Estrella", name_en: "The Star", type: "major", number: 17, keywords_up: "Esperanza, fe, propósito, renovación, espiritualidad", keywords_rev: "Falta de fe, desesperación, desconexión", img: "assets/images/placeholder.png" },
    { id: 18, name_es: "La Luna", name_en: "The Moon", type: "major", number: 18, keywords_up: "Ilusión, miedo, ansiedad, subconsciente", keywords_rev: "Liberación del miedo, infelicidad, confusión", img: "assets/images/placeholder.png" },
    { id: 19, name_es: "El Sol", name_en: "The Sun", type: "major", number: 19, keywords_up: "Positividad, diversión, calidez, éxito, vitalidad", keywords_rev: "Niño interior, sentirse deprimido", img: "assets/images/placeholder.png" },
    { id: 20, name_es: "El Juicio", name_en: "Judgement", type: "major", number: 20, keywords_up: "Juicio, renacimiento, llamada interior, absolución", keywords_rev: "Duda, falta de autoconciencia", img: "assets/images/placeholder.png" },
    { id: 21, name_es: "El Mundo", name_en: "The World", type: "major", number: 21, keywords_up: "Completación, integración, logro, viaje", keywords_rev: "Falta de cierre, atajos, retrasos", img: "assets/images/placeholder.png" },

    // Minor Arcana - Wands (Bastos)
    { id: 22, name_es: "As de Bastos", name_en: "Ace of Wands", type: "minor", suit: "bastos", number: 1, keywords_up: "Inspiración, nuevo comienzo", keywords_rev: "Retrasos, falta de motivación" },
    { id: 23, name_es: "Dos de Bastos", name_en: "Two of Wands", type: "minor", suit: "bastos", number: 2, keywords_up: "Planificación, decisiones futuras", keywords_rev: "Miedo a lo desconocido, mala planificación" },
    { id: 24, name_es: "Tres de Bastos", name_en: "Three of Wands", type: "minor", suit: "bastos", number: 3, keywords_up: "Progreso, expansión, previsión", keywords_rev: "Obstáculos, retrasos, frustración" },
    { id: 25, name_es: "Cuatro de Bastos", name_en: "Four of Wands", type: "minor", suit: "bastos", number: 4, keywords_up: "Celebración, armonía, hogar", keywords_rev: "Conflicto en el hogar, inestabilidad" },
    { id: 26, name_es: "Cinco de Bastos", name_en: "Five of Wands", type: "minor", suit: "bastos", number: 5, keywords_up: "Conflicto, desacuerdo, competencia", keywords_rev: "Evitar el conflicto, respeto a la diversidad" },
    { id: 27, name_es: "Seis de Bastos", name_en: "Six of Wands", type: "minor", suit: "bastos", number: 6, keywords_up: "Éxito, reconocimiento, victoria", keywords_rev: "Egoísmo, caída en desgracia" },
    { id: 28, name_es: "Siete de Bastos", name_en: "Seven of Wands", type: "minor", suit: "bastos", number: 7, keywords_up: "Desafío, competencia, protección", keywords_rev: "Rendirse, sentirse abrumado" },
    { id: 29, name_es: "Ocho de Bastos", name_en: "Eight of Wands", type: "minor", suit: "bastos", number: 8, keywords_up: "Movimiento rápido, acción, noticias", keywords_rev: "Retrasos, frustración, esperar" },
    { id: 30, name_es: "Nueve de Bastos", name_en: "Nine of Wands", type: "minor", suit: "bastos", number: 9, keywords_up: "Resiliencia, coraje, persistencia", keywords_rev: "Agotamiento, fatiga, dudas" },
    { id: 31, name_es: "Diez de Bastos", name_en: "Ten of Wands", type: "minor", suit: "bastos", number: 10, keywords_up: "Carga, responsabilidad, trabajo duro", keywords_rev: "Colapso, incapacidad de delegar" },
    { id: 32, name_es: "Paje de Bastos", name_en: "Page of Wands", type: "minor", suit: "bastos", number: 11, keywords_up: "Entusiasmo, exploración, descubrimiento", keywords_rev: "Contratiempos, nuevas ideas bloqueadas" },
    { id: 33, name_es: "Caballero de Bastos", name_en: "Knight of Wands", type: "minor", suit: "bastos", number: 12, keywords_up: "Energía, pasión, aventura, impulsividad", keywords_rev: "Prisa, dispersión, frustración" },
    { id: 34, name_es: "Reina de Bastos", name_en: "Queen of Wands", type: "minor", suit: "bastos", number: 13, keywords_up: "Exuberancia, calidez, determinación", keywords_rev: "Celos, inseguridad, egoísmo" },
    { id: 35, name_es: "Rey de Bastos", name_en: "King of Wands", type: "minor", suit: "bastos", number: 14, keywords_up: "Liderazgo, visión, honor", keywords_rev: "Impulsividad, expectativas irreales" },

    // Minor Arcana - Cups (Copas)
    { id: 36, name_es: "As de Copas", name_en: "Ace of Cups", type: "minor", suit: "copas", number: 1, keywords_up: "Amor, nueva relación, compasión", keywords_rev: "Amor propio, intuición reprimida" },
    { id: 37, name_es: "Dos de Copas", name_en: "Two of Cups", type: "minor", suit: "copas", number: 2, keywords_up: "Asociación unificada, atracción", keywords_rev: "Ruptura, desequilibrio" },
    { id: 38, name_es: "Tres de Copas", name_en: "Three of Cups", type: "minor", suit: "copas", number: 3, keywords_up: "Comunidad, amistad, creatividad", keywords_rev: "Independencia, soledad" },
    { id: 39, name_es: "Cuatro de Copas", name_en: "Four of Cups", type: "minor", suit: "copas", number: 4, keywords_up: "Apatía, contemplación, desconexión", keywords_rev: "Claridad repentina, conciencia" },
    { id: 40, name_es: "Cinco de Copas", name_en: "Five of Cups", type: "minor", suit: "copas", number: 5, keywords_up: "Pérdida, dolor, decepción", keywords_rev: "Aceptación, perdón, seguir adelante" },
    { id: 41, name_es: "Seis de Copas", name_en: "Six of Cups", type: "minor", suit: "copas", number: 6, keywords_up: "Nostalgia, recuerdos, infancia", keywords_rev: "Vivir en el pasado, no perdonar" },
    { id: 42, name_es: "Siete de Copas", name_en: "Seven of Cups", type: "minor", suit: "copas", number: 7, keywords_up: "Ilusión, opciones, sueños", keywords_rev: "Tentación, falta de propósito" },
    { id: 43, name_es: "Ocho de Copas", name_en: "Eight of Cups", type: "minor", suit: "copas", number: 8, keywords_up: "Abandono, decepción, retirada", keywords_rev: "Miedo al cambio, estancamiento" },
    { id: 44, name_es: "Nueve de Copas", name_en: "Nine of Cups", type: "minor", suit: "copas", number: 9, keywords_up: "Satisfacción, gratitud, deseo cumplido", keywords_rev: "Insatisfacción, materialismo" },
    { id: 45, name_es: "Diez de Copas", name_en: "Ten of Cups", type: "minor", suit: "copas", number: 10, keywords_up: "Felicidad divina, alineación, familia", keywords_rev: "Desconexión, valores desalineados" },
    { id: 46, name_es: "Paje de Copas", name_en: "Page of Cups", type: "minor", suit: "copas", number: 11, keywords_up: "Curiosidad creativa, mensajes, intuición", keywords_rev: "Bloqueo creativo, inmadurez emocional" },
    { id: 47, name_es: "Caballero de Copas", name_en: "Knight of Cups", type: "minor", suit: "copas", number: 12, keywords_up: "Romance, encanto, imaginación", keywords_rev: "Celos, mal humor, desilusión" },
    { id: 48, name_es: "Reina de Copas", name_en: "Queen of Cups", type: "minor", suit: "copas", number: 13, keywords_up: "Compasión, calma, comodidad", keywords_rev: "Mártir, inseguridad, dependencia" },
    { id: 49, name_es: "Rey de Copas", name_en: "King of Cups", type: "minor", suit: "copas", number: 14, keywords_up: "Equilibrio emocional, control, generosidad", keywords_rev: "Manipulación, mal humor" },

    // Minor Arcana - Swords (Espadas)
    { id: 50, name_es: "As de Espadas", name_en: "Ace of Swords", type: "minor", suit: "espadas", number: 1, keywords_up: "Avance, claridad, verdad nítida", keywords_rev: "Confusión, caos, falta de claridad" },
    { id: 51, name_es: "Dos de Espadas", name_en: "Two of Swords", type: "minor", suit: "espadas", number: 2, keywords_up: "Decisión difícil, estancamiento", keywords_rev: "Indecisión, confusión, sobrecarga" },
    { id: 52, name_es: "Tres de Espadas", name_en: "Three of Swords", type: "minor", suit: "espadas", number: 3, keywords_up: "Dolor, tristeza, separación", keywords_rev: "Perdón, recuperación, optimismo" },
    { id: 53, name_es: "Cuatro de Espadas", name_en: "Four of Swords", type: "minor", suit: "espadas", number: 4, keywords_up: "Descanso, recuperación, contemplación", keywords_rev: "Agotamiento, estrés, inquietud" },
    { id: 54, name_es: "Cinco de Espadas", name_en: "Five of Swords", type: "minor", suit: "espadas", number: 5, keywords_up: "Conflicto, derrota, ganar a toda costa", keywords_rev: "Reconciliación, perdón" },
    { id: 55, name_es: "Seis de Espadas", name_en: "Six of Swords", type: "minor", suit: "espadas", number: 6, keywords_up: "Transición, dejar atrás, viaje", keywords_rev: "Resistencia al cambio, equipaje" },
    { id: 56, name_es: "Siete de Espadas", name_en: "Seven of Swords", type: "minor", suit: "espadas", number: 7, keywords_up: "Estrategia, engaño, sigilo", keywords_rev: "Confesión, conciencia, verdad" },
    { id: 57, name_es: "Ocho de Espadas", name_en: "Eight of Swords", type: "minor", suit: "espadas", number: 8, keywords_up: "Restricción, victimización, miedo", keywords_rev: "Nuevas perspectivas, libertad" },
    { id: 58, name_es: "Nueve de Espadas", name_en: "Nine of Swords", type: "minor", suit: "espadas", number: 9, keywords_up: "Ansiedad, preocupación, miedo, pesadillas", keywords_rev: "Esperanza, alcanzar la luz, desesperación" },
    { id: 59, name_es: "Diez de Espadas", name_en: "Ten of Swords", type: "minor", suit: "espadas", number: 10, keywords_up: "Traición, final doloroso, crisis", keywords_rev: "Recuperación, regeneración" },
    { id: 60, name_es: "Paje de Espadas", name_en: "Page of Swords", type: "minor", suit: "espadas", number: 11, keywords_up: "Curiosidad, inquietud, energía mental", keywords_rev: "Chismes, hablar sin actuar" },
    { id: 61, name_es: "Caballero de Espadas", name_en: "Knight of Swords", type: "minor", suit: "espadas", number: 12, keywords_up: "Acción, impulsividad, ambición", keywords_rev: "Imprevisibilidad, brusquedad" },
    { id: 62, name_es: "Reina de Espadas", name_en: "Queen of Swords", type: "minor", suit: "espadas", number: 13, keywords_up: "Independencia, percepción imparcial, claridad", keywords_rev: "Frialdad, amargura, crueldad" },
    { id: 63, name_es: "Rey de Espadas", name_en: "King of Swords", type: "minor", suit: "espadas", number: 14, keywords_up: "Autoridad mental, verdad, intelecto", keywords_rev: "Manipulación, tiranía, abuso" },

    // Minor Arcana - Pentacles (Oros)
    { id: 64, name_es: "As de Oros", name_en: "Ace of Pentacles", type: "minor", suit: "oros", number: 1, keywords_up: "Oportunidad, prosperidad, nuevo comienzo", keywords_rev: "Oportunidad perdida, mala inversión" },
    { id: 65, name_es: "Dos de Oros", name_en: "Two of Pentacles", type: "minor", suit: "oros", number: 2, keywords_up: "Equilibrio, adaptabilidad, gestión del tiempo", keywords_rev: "Desorganización, caos financiero" },
    { id: 66, name_es: "Tres de Oros", name_en: "Three of Pentacles", type: "minor", suit: "oros", number: 3, keywords_up: "Trabajo en equipo, colaboración, aprendizaje", keywords_rev: "Falta de cohesión, competencia" },
    { id: 67, name_es: "Cuatro de Oros", name_en: "Four of Pentacles", type: "minor", suit: "oros", number: 4, keywords_up: "Conservación, seguridad, frugalidad", keywords_rev: "Avaricia, gasto excesivo" },
    { id: 68, name_es: "Cinco de Oros", name_en: "Five of Pentacles", type: "minor", suit: "oros", number: 5, keywords_up: "Necesidad, pobreza, aislamiento", keywords_rev: "Recuperación, caridad, mejora" },
    { id: 69, name_es: "Seis de Oros", name_en: "Six of Pentacles", type: "minor", suit: "oros", number: 6, keywords_up: "Generosidad, caridad, dar y recibir", keywords_rev: "Deudas, egoísmo, dominación" },
    { id: 70, name_es: "Siete de Oros", name_en: "Seven of Pentacles", type: "minor", suit: "oros", number: 7, keywords_up: "Perseverancia, largo plazo, cosecha", keywords_rev: "Falta de recompensa, impaciencia" },
    { id: 71, name_es: "Ocho de Oros", name_en: "Eight of Pentacles", type: "minor", suit: "oros", number: 8, keywords_up: "Aprendizaje, maestría, detalle", keywords_rev: "Perfeccionismo, falta de ambición" },
    { id: 72, name_es: "Nueve de Oros", name_en: "Nine of Pentacles", type: "minor", suit: "oros", number: 9, keywords_up: "Abundancia, lujo, autosuficiencia", keywords_rev: "Dependencia financiera, malas inversiones" },
    { id: 73, name_es: "Diez de Oros", name_en: "Ten of Pentacles", type: "minor", suit: "oros", number: 10, keywords_up: "Legado, herencia, culminación", keywords_rev: "Fracaso financiero, pérdida" },
    { id: 74, name_es: "Paje de Oros", name_en: "Page of Pentacles", type: "minor", suit: "oros", number: 11, keywords_up: "Manifestación, oportunidad financiera, estudio", keywords_rev: "Falta de progreso, procrastinación" },
    { id: 75, name_es: "Caballero de Oros", name_en: "Knight of Pentacles", type: "minor", suit: "oros", number: 12, keywords_up: "Eficiencia, trabajo duro, responsabilidad", keywords_rev: "Pereza, obsesión, aburrimiento" },
    { id: 76, name_es: "Reina de Oros", name_en: "Queen of Pentacles", type: "minor", suit: "oros", number: 13, keywords_up: "Practicidad, comodidad, seguridad financiera", keywords_rev: "Desequilibrio trabajo-vida, celos" },
    { id: 77, name_es: "Rey de Oros", name_en: "King of Pentacles", type: "minor", suit: "oros", number: 14, keywords_up: "Riqueza, negocios, liderazgo, seguridad", keywords_rev: "Codicia, indulgencia, ineptitud" }
];
